name: Application

on:
  push:


permissions:
  id-token: write
  contents: read


jobs:

  application:
    name: Application Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Package Installer (poetry)
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true

      - name: Linter (ruff)
        shell: bash
        run: ruff format

      - name: Type Checks (mypy)
        shell: bash
        run: mypy .

      - name: Unit Tests (pytest)
        shell: bash
        run: |
          pytest --cov=./ tests/